### ISSUE TITLE
Comparison to swagger-codegen?

### ISSUE THREAD

**Issue by john-goldsmith** [DiegoZoracKy/oas-client#1]
I'm curious about the pros and cons of this library over [`swagger-codegen`](https://github.com/swagger-api/swagger-codegen) (specifically the JavaScript generator).  Thoughts?

**Comment by DiegoZoracKy** [comment]
From what I remember of swagger-codegen, it generates static files instead of doing it on runtime. Also, when I tried it (a long time ago) it wasn't easy as just passing in the spec and then everything was already setup. I also don't remember about the feature to accept any data as a parameter without defining explicitly where they should be included (qs, path, headers, etc. )

Do you know more about it for us to do a better comparison between them? 

Thanks for bringing that discussion.

**Comment by john-goldsmith** [comment]
From my understanding, Swagger offers two tools when it comes to JavaScript-specific behavior: 1) [`swagger-codegen`](https://github.com/swagger-api/swagger-codegen) which yields static files and 2) [`swagger-js`](https://github.com/swagger-api/swagger-js) which I think is more akin to your runtime library.  I'm currently using the former in a real-world project and so far I'm satisfied with it, at least from a [configuration](https://github.com/swagger-api/swagger-codegen/blob/4607a90d7b69463a0ae8fc94fac68fc95d80965e/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java#L88-L99) and ease-of-consumption standpoint.  It allows for generating an entire SDK that lives separately from all other apps and gets packaged up as an NPM package.  I haven't yet (quantitatively) evaluated if it adds too much overhead to bundle size, etc.

I had [a question](https://github.com/swagger-api/swagger-js/issues/1287) regarding the viability of a runtime-style approach given the potential cost of requesting an entire OpenAPI spec.  Frankly, I didn't receive a satisfactory answer -- maybe you can weigh in on this?

> I also don't remember about the feature to accept any data as a parameter without defining explicitly where they should be included (qs, path, headers, etc.)

I don't quite follow -- can you elaborate?  Defining incoming data/params is supported by both the v2 and v3 spec, and `swagger-codegen` creates models and validation based on them.

**Comment by DiegoZoracKy** [comment]
Hi @john-goldsmith. As you asked let me give you some comments on top of what you wrote.

> I had a question regarding the viability of a runtime-style approach given the potential cost of requesting an entire OpenAPI spec. Frankly, I didn't receive a satisfactory answer -- maybe you can weigh in on this?

I believe that this is a genuine question, however, right before you also said: 

> I haven't yet (quantitatively) evaluated if it adds too much overhead to bundle size, etc.

In my point of view, both cases belong to the same concern: Request cost. In the same way that you are worried about the cost of requesting the specification you also should be worried about requesting the generated code, as in the end both will incur in code being downloaded by the client. 

Besides that, I've never seen a specification big enough to raise a flag like that. We should remember that in the end the code will be transferred compressed (gzip), and the transport cost will be possibly very low (I would guess that a really long specification will still be way lower than 10kb). You could try to gzip some of yours to see the result size.

I don't like much their *swagger-codegen* strategy, I prefer to have it in a more simple way as the *swagger-js* does. I didn't know about the latter, and looking at its *"Constructor and methods"* example, it seems that some aspects are handled in a similar way to that found on *oas-client*.

Looking at their lib, at first I missed a way to define default parameters and headers on the fly (in my opinion, essential to handle authorization tokens). 

Also, as they are passing in all the request parameters as objects' root keys, I don't know if they support a way for one to define specifically where some of the parameters should go. Regarding that case *oas-client* supports it. The expected parameter is: `{ data, path, query, headers, cookie, body }`.

These are some differences I've noted at a first look. Maybe I'll try to use it at some point to see how it goes. Thanks for letting me know about it.

**Comment by john-goldsmith** [comment]
All valid points -- thanks for taking the time to give some feedback!
